import { Card, CardContent, CardHeader } from "@/components/ui/card";
import Image from "next/image";
import React from "react";
import Navbar from "../CustomComponents/Navbar";
import Link from "next/link";

const page = () => {
  return (
    <>
      <Navbar />

      <div className="flex items-center justify-between gap-[50px] mx-auto max-w-[70%] mt-[70px] h-[80%]">
        <Card className="w-[50%] cursor-pointer hover:scale-[1.03] hover:border hover:border-white transition duration-300 ease">
          <Link href="/ai">
            <CardHeader>
              <Image
                src="/ai.svg"
                alt="ai svg"
                className="block mx-auto"
                width={200}
                height={200}
              />
            </CardHeader>
            <CardContent className="text-center ">
              <h1 className="text-3xl font-bold tracking-wider">
                AI Generated Fill In The Blanks Questions !!
              </h1>
              <p className="py-5 text-muted-background">
                Challenge your knowledge with AI-powered quizzes! Fill in the
                blanks and choose the right answers across various categories,
                all generated by artificial intelligence.
              </p>
            </CardContent>
          </Link>
        </Card>
        <Card className="w-[50%] cursor-pointer hover:scale-[1.03] hover:border hover:border-white transition duration-300 ease">
          <Link href="/mcq">
            <CardHeader>
              <Image
                src="/category.svg"
                alt="categorysvg"
                className="block mx-auto"
                width={200}
                height={200}
              />
            </CardHeader>
            <CardContent className="text-center ">
              <h1 className="text-3xl font-bold tracking-wider">
                MCQ Questions Across various Categories !!
              </h1>
              <p className="py-5 text-muted-background">
                Test your skills with questions across Categories !! From
                history to science, answer multiple-choice questions designed
                spanning a range of topics.
              </p>
            </CardContent>
          </Link>
        </Card>
      </div>
    </>
  );
};

export default page;
